# Generated by Django 6.0.5 on 2026-06-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Sesión Actual'),
        ),
    ]
