# Generated by Django 6.0.5 on 2026-06-02 04:41

import modules.personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', modules.personal.models.EncryptedCharField(max_length=255, verbose_name='Nombres')),
                ('apellidos', modules.personal.models.EncryptedCharField(max_length=255, verbose_name='Apellidos')),
                ('cedula', modules.personal.models.EncryptedCharField(max_length=255, unique=True, verbose_name='Cédula de Identidad')),
                ('direccion', modules.personal.models.EncryptedTextField(blank=True, null=True, verbose_name='Dirección')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad Médica')),
                ('horas_max_semanales', models.IntegerField(default=48, verbose_name='Límite Semanal (horas)')),
                ('apto_nocturno', models.BooleanField(default=True, help_text='Indica si el profesional tiene aptitud médica para trabajar en horario nocturno', verbose_name='Apto para Turnos Nocturnos')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_personal/', verbose_name='Fotografía de Perfil')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Personal Médico',
                'verbose_name_plural': 'Personal Médico',
                'ordering': ['-creado_en'],
            },
        ),
    ]
