# Generated by Django 6.0.5 on 2026-06-03 12:50

import modules.personal.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='correo',
            field=modules.personal.models.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
