# Generated by Django 6.0.5 on 2026-06-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_personal_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='antiguedad_meses',
            field=models.IntegerField(default=0, verbose_name='Antigüedad (meses)'),
        ),
        migrations.AddField(
            model_name='personal',
            name='categoria',
            field=models.CharField(choices=[('Especialista', 'Médico Especialista'), ('General', 'Médico General'), ('Enfermera', 'Enfermera Licenciada'), ('Tecnico', 'Técnico / Paramédico'), ('Auxiliar', 'Auxiliar de Enfermería')], default='Especialista', max_length=50, verbose_name='Categoría Profesional'),
        ),
        migrations.AddField(
            model_name='personal',
            name='en_vacaciones',
            field=models.BooleanField(default=False, verbose_name='En Vacaciones'),
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_fin_permiso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin de Permiso'),
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_fin_vacaciones',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin de Vacaciones'),
        ),
        migrations.AddField(
            model_name='personal',
            name='haber_basico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Haber Básico (Salario)'),
        ),
        migrations.AddField(
            model_name='personal',
            name='permiso_activo',
            field=models.BooleanField(default=False, verbose_name='Permiso Activo'),
        ),
        migrations.AddField(
            model_name='personal',
            name='sala_habitual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sala / Consultorio Habitual'),
        ),
        migrations.AddField(
            model_name='personal',
            name='servicio_asignado',
            field=models.CharField(choices=[('Emergencias', 'Emergencias / Urgencias'), ('UCI', 'Unidad de Cuidados Intensivos (UCI)'), ('Hospitalizacion', 'Hospitalización (Planta)'), ('Consulta', 'Consulta Externa'), ('Quirofano', 'Quirófano / Cirugía'), ('Laboratorio', 'Laboratorio / Imagenología')], default='Consulta', max_length=50, verbose_name='Servicio Asignado'),
        ),
        migrations.AddField(
            model_name='personal',
            name='voluntario_feriados',
            field=models.BooleanField(default=False, verbose_name='Voluntario para Feriados'),
        ),
    ]
