# Generated by Django 6.0.5 on 2026-06-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_personal_antiguedad_meses_personal_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Vacaciones', 'Vacaciones Anuales'), ('Enfermedad', 'Baja por Enfermedad'), ('Maternidad_Paternidad', 'Licencia Maternidad/Paternidad'), ('Luto', 'Licencia por Luto'), ('Especial', 'Permiso Especial')], max_length=50, verbose_name='Tipo de Permiso')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('motivo', models.TextField(verbose_name='Motivo o Justificación')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Aprobación'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20, verbose_name='Estado de Solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_permiso', to='personal.personal', verbose_name='Personal Médico')),
            ],
            options={
                'verbose_name': 'Solicitud de Permiso',
                'verbose_name_plural': 'Solicitudes de Permisos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
