# Generated by Django 6.0.5 on 2026-06-02 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_conocimiento', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(default='08:00', verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(default='16:00', verbose_name='Hora de Fin')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='base_conocimiento.consultorio', verbose_name='Consultorio')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='personal.personal', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Asignación de Turno',
                'verbose_name_plural': 'Asignaciones de Turno',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
