# Generated by Django 6.0.5 on 2026-06-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_solicitudpermiso'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo del Cambio')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Aceptación'), ('Aceptado', 'Aceptado por Colega (Esperando Admin)'), ('Aprobado_Admin', 'Aprobado por Administrador'), ('Rechazado', 'Rechazado / Vencido')], default='Pendiente', max_length=20, verbose_name='Estado de la Solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('medico_reemplazante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_aceptados', to='personal.personal', verbose_name='Médico Reemplazante (Aceptó el cambio)')),
                ('medico_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_solicitados', to='personal.personal', verbose_name='Médico Solicitante')),
                ('turno_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='turnos.asignacionturno', verbose_name='Turno Original')),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Turno',
                'verbose_name_plural': 'Solicitudes de Cambio de Turno',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
