# Generated by Django 6.0.5 on 2026-06-02 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Ejemplo: HORAS_DESCANSO_MIN', max_length=100, unique=True, verbose_name='Clave')),
                ('valor', models.JSONField(help_text='Valor del hecho (int, string, lista, diccionario)', verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Hecho',
                'verbose_name_plural': 'Hechos',
            },
        ),
        migrations.CreateModel(
            name='NormativaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Tarifa', help_text='Ej: Tarifa Base, Recargo Nocturno', max_length=100, verbose_name='Nombre')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Aplica desde esta hora (opcional)', null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, help_text='Aplica hasta esta hora (opcional)', null=True, verbose_name='Hora de Fin')),
                ('tarifa_por_hora', models.DecimalField(decimal_places=2, help_text='Pago por hora en Bolivianos', max_digits=8, verbose_name='Tarifa por Hora (Bs.)')),
                ('justificacion_legal', models.TextField(help_text='Ej: Ley General del Trabajo Art. 55', verbose_name='Justificación Legal')),
            ],
            options={
                'verbose_name': 'Normativa Financiera',
                'verbose_name_plural': 'Normativas Financieras',
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Planta Baja, Piso 1', max_length=50, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
            },
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('condicion', models.JSONField(help_text='Estructura lógica en formato JSON', verbose_name='Condición')),
                ('accion', models.JSONField(help_text='Acción a ejecutar en formato JSON', verbose_name='Acción')),
                ('prioridad', models.IntegerField(default=10, help_text='Mayor prioridad se evalúa primero', verbose_name='Prioridad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Regla',
                'verbose_name_plural': 'Reglas',
                'ordering': ['-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='ServicioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Urgencias, Pediatría, UCI', max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('capacidad_concurrente', models.IntegerField(default=1, help_text='Máx. de médicos simultáneos en este servicio', verbose_name='Capacidad Concurrente')),
            ],
            options={
                'verbose_name': 'Servicio Médico',
                'verbose_name_plural': 'Servicios Médicos',
            },
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_o_numero', models.CharField(help_text='Ej: Consultorio 101, Cama 5', max_length=50, verbose_name='Número o Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultorios', to='base_conocimiento.piso', verbose_name='Piso')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultorios', to='base_conocimiento.serviciomedico', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
                'unique_together': {('nombre_o_numero', 'piso')},
            },
        ),
    ]
