# Generated by Django 6.0.5 on 2026-06-03 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción Realizada')),
                ('detalles', models.TextField(verbose_name='Detalles de la Acción')),
                ('nivel_severidad', models.CharField(choices=[('INFO', 'Informativo'), ('ADVERTENCIA', 'Advertencia'), ('CRITICO', 'Crítico')], default='INFO', max_length=20, verbose_name='Severidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción. Nulo si fue un proceso automático del sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario / Sistema')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
