# Generated by Django 6.0.5 on 2026-06-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='Dirección IP')),
                ('reason', models.CharField(default='Acceso a Honeypot', max_length=255, verbose_name='Motivo del Bloqueo')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IP en Lista Negra',
                'verbose_name_plural': 'IPs en Lista Negra',
            },
        ),
    ]
