# Generated by Django 6.0.5 on 2026-06-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_blacklistedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoria',
            name='motivo',
            field=models.TextField(blank=True, help_text='Justificación si es una acción manual forzada.', null=True, verbose_name='Motivo de la Acción'),
        ),
    ]
